backup: add multiple operations to location check (#1509)
Sample error results

Server:

```
[support@ip-172-31-3-54 ~]$ sctool backup --dry-run -L s3:scylla-manager-backup-testaaaa -c test
Error: failed to get backup target: location is not accessible
 52.28.144.202: agent [HTTP 404] no put permission - make sure the location is correct and credentials are set, to debug SSH to 52.28.144.202 and run 'scylla-manager-agent check-location -L s3:scylla-manager-backup-testaaaa --debug'
(for more info grep logs for trace ID: JbbWKhlLSiuYWnNsA--7jQ)
```

Agent:

```
[support@ip-172-31-0-11 ~]$ scylla-manager-agent check-location -L aaa:s3:scylla-manager-backup-testaaa
 FAILED: no put permission
 [support@ip-172-31-0-11 ~]$ scylla-manager-agent check-location -L aaa:s3:scylla-manager-backup-testaaa --debug
 {"L":"INFO","T":"2019-12-19T09:59:58.472Z","N":"rclone","M":"registered s3 provider [name=s3, region=eu-central-1, upload_concurrency=5]"}
 {"L":"INFO","T":"2019-12-19T09:59:58.785Z","N":"rclone","M":"S3 bucket scylla-manager-backup-testaaa: Waiting for checks to finish"}
 {"L":"INFO","T":"2019-12-19T09:59:58.785Z","N":"rclone","M":"S3 bucket scylla-manager-backup-testaaa: Waiting for transfers to finish"}
 {"L":"ERROR","T":"2019-12-19T09:59:58.864Z","N":"rclone","M":"check-fs-permissions057466645/scylla-manager-test: Failed to copy: s3 upload: 404 Not Found: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>scylla-manager-backup-testaaa</BucketName><RequestId>D0BE57BD44691849</RequestId><HostId>4JIkxt/PhplwRz1zL0Tor3uyDbMHk4h07B+4DfWZlJ17B9wOPwzwrDtUwJEQeEWT8BI4uV6e+9s=</HostId></Error>","S":"github.com/scylladb/go-log.Logger.log\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/scylladb/go-log/logger.go:92\ngithub.com/scylladb/go-log.Logger.Error\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/scylladb/go-log/logger.go:75\ngithub.com/scylladb/mermaid/pkg/rclone.RedirectLogPrint.func1\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/rclone/rclone/fs/log.go:107\ngithub.com/rclone/rclone/fs.Errorf\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/rclone/rclone/fs/log.go:122\ngithub.com/rclone/rclone/fs/operations.Copy\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/rclone/rclone/fs/operations/operations.go:412\ngithub.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove\n\t/home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/vendor/github.com/rclone/rclone/fs/sync/sync.go:297"}
 FAILED: no put permission
```

Fixes #1509
Fixes #1456
Fixes #1515

Signed-off-by: Michał Matczuk <michal@scylladb.com>