cmd/service/backup: sctool validation fixes (#1528)
```
$ sctool backup -c test --dry-run -L asdas
Error: failed to get backup target: invalid location "asdas", the format is [dc:]<provider>:<path> ex. s3:my-bucket, the path must be DNS compliant
Trace ID: w97yjXJdQ7WYqKeXOvIXpw (grep in scylla-manager logs)

$ sctool backup -c test --dry-run -L s3:a
Error: failed to get backup target: location is not accessible
 192.168.100.13: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.13 and run "scylla-manager-agent check-location -L s3:a --debug"
 192.168.100.12: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.12 and run "scylla-manager-agent check-location -L s3:a --debug"
 192.168.100.21: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.21 and run "scylla-manager-agent check-location -L s3:a --debug"
 192.168.100.22: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.22 and run "scylla-manager-agent check-location -L s3:a --debug"
 192.168.100.23: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.23 and run "scylla-manager-agent check-location -L s3:a --debug"
 192.168.100.11: agent [HTTP 404] no list permission - make sure the location is correct and credentials are set, to debug SSH to 192.168.100.11 and run "scylla-manager-agent check-location -L s3:a --debug"
Trace ID: 9lqnuvTxQiWQG6wog0mlgA (grep in scylla-manager logs)

$ sctool backup -c test --dry-run -L s3:a --rate-limit s
Error: failed to get backup target: invalid limit "s", the format is [dc:]<number>
Trace ID: R17sDw-HSFutMg21iQR5YA (grep in scylla-manager logs)

$ sctool backup -c test --dry-run -L s3:a --rate-limit dcX:3f
Error: failed to get backup target: invalid limit "dcX:3f", the format is [dc:]<number>
Trace ID: eWAlDMGTQUiXkbYxBzYqRg (grep in scylla-manager logs)
```

Same for other limits

Fixes #1528

Signed-off-by: Michał Matczuk <michal@scylladb.com>