sctool: Print per cluster errors in status and tasks (#2373)
With the patch, in presense of an error, the error is printed and sctool continues with other clusters.

```
$ sctool status -c af907db9-499d-4856-b53f-720b5f87c02f
Error: failed to get cluster "af907db9-499d-4856-b53f-720b5f87c02f" status: a terrible error
Trace ID: sYQ_1YIOSTG01CkISJSeUg (grep in scylla-manager logs)

 michal@lh:scylla/scylla-manager (mmt/sctool_multiple_clusters_fix)$ ./sctool status
Cluster: test (37313c9a-509a-41c1-91f7-54f87b911050)
Datacenter: dc1
╭────┬────────────┬──────────┬───────────┬────────────────┬──────────┬──────┬──────────┬────────┬──────────┬──────────────────────────────────────╮
│    │ Alternator │ CQL      │ REST      │ Address        │ Uptime   │ CPUs │ Memory   │ Scylla │ Agent    │ Host ID                              │
├────┼────────────┼──────────┼───────────┼────────────────┼──────────┼──────┼──────────┼────────┼──────────┼──────────────────────────────────────┤
│ UN │ UP (15ms)  │ UP (8ms) │ UP (6ms)  │ 192.168.100.11 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ b2e7fa18-0f19-4386-93b1-831256682a1d │
│ UN │ UP (9ms)   │ UP (7ms) │ UP (5ms)  │ 192.168.100.12 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ 3a662b77-6c6f-42aa-b820-80bc65904e00 │
│ UN │ UP (12ms)  │ UP (4ms) │ UP (10ms) │ 192.168.100.13 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ abce45d4-1a82-4124-ad01-562b51d4c83c │
╰────┴────────────┴──────────┴───────────┴────────────────┴──────────┴──────┴──────────┴────────┴──────────┴──────────────────────────────────────╯
Datacenter: dc2
╭────┬────────────┬──────────┬───────────┬────────────────┬──────────┬──────┬──────────┬────────┬──────────┬──────────────────────────────────────╮
│    │ Alternator │ CQL      │ REST      │ Address        │ Uptime   │ CPUs │ Memory   │ Scylla │ Agent    │ Host ID                              │
├────┼────────────┼──────────┼───────────┼────────────────┼──────────┼──────┼──────────┼────────┼──────────┼──────────────────────────────────────┤
│ UN │ UP (11ms)  │ UP (4ms) │ UP (6ms)  │ 192.168.100.21 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ 0cefc5f7-8087-4ce3-b93b-44b7cef26fe7 │
│ UN │ UP (6ms)   │ UP (2ms) │ UP (5ms)  │ 192.168.100.22 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ 8858d20a-21e6-4c2b-9399-4c0ed2b902fb │
│ UN │ UP (5ms)   │ UP (5ms) │ UP (11ms) │ 192.168.100.23 │ 2h50m51s │ 4    │ 31.13GiB │ 4.2.1  │ Snapshot │ 3e5530d4-2c01-48cc-be45-1fac570135a1 │
╰────┴────────────┴──────────┴───────────┴────────────────┴──────────┴──────┴──────────┴────────┴──────────┴──────────────────────────────────────╯
Cluster:  (af907db9-499d-4856-b53f-720b5f87c02f)
Error: failed to get cluster "af907db9-499d-4856-b53f-720b5f87c02f" status: a terrible error
Trace ID: wP2zUNBmSSucNvQAHkAp1w (grep in scylla-manager logs)

```

Fixes #2373

(cherry picked from commit c12ada4c8fe3f98c8073e1e946ef1e70d051433a)