mermaid: force go build to use vendored packages
If apcera/termtables is not cached in $GOCACHE then go build fails with:

    $ make dev-server
    ==> Building scylla-manager
    go: finding github.com/apcera/termtables v0.0.0-20170405184538-bcbc5dc54055
            ERROR: Repository not found.
            fatal: Could not read from remote repository.

            Please make sure you have the correct access rights
            and the repository exists.
    go: error loading module requirements
    make: *** [Makefile:112: dev-server] Error 1

This PR forces go build to use vendored copy of apcera/termtables, thus
fixes the build.

Relates to #951.