swagger,sctool,restapi: sctool suspend support (#2382)
Boilerplate implementing sctool suspend and resume functions

```
$ sctool suspend -c test
$ sctool task list
Cluster: test (0a17ddbc-c7fd-40de-ba64-ff524a1ac920)
SUSPENDED
╭─────────────────────────────────────────────────────────────┬───────────┬───────────────────────────────┬────────╮
│ Task                                                        │ Arguments │ Next run                      │ Status │
├─────────────────────────────────────────────────────────────┼───────────┼───────────────────────────────┼────────┤
│ healthcheck_rest/4144a1de-37d6-4a07-9751-c239632331b8       │           │ 11 Dec 20 18:24:50 CET (+1m)  │ NEW    │
│ healthcheck/119c7e78-f607-4266-9904-e6f4d88a3ceb            │           │ 11 Dec 20 18:33:20 CET (+15s) │ NEW    │
│ healthcheck_alternator/8a6f0114-7718-4075-ad4a-860383461368 │           │ 11 Dec 20 18:33:20 CET (+15s) │ NEW    │
│ repair/924eaad7-f129-4d87-a0f3-431e4f2c32ce                 │           │                               │ NEW    │
╰─────────────────────────────────────────────────────────────┴───────────┴───────────────────────────────┴────────╯
$ sctool suspend -c test
Error: failed to suspend: cluster already suspended
$ sctool resume --start-tasks -c test
```

(cherry picked from commit 500a4a0d4fad5610f2010763073b60901c5fe390)