sched: fixed flaky tests
```
--- FAIL: TestServiceScheduleIntegration (26.06s)
    --- PASS: TestServiceScheduleIntegration/task_put_once (0.40s)
    --- FAIL: TestServiceScheduleIntegration/task_put_once_update (0.34s)
        <autogenerated>:1: Unexpected call to *sched.MockRunner.Run([context.Background.WithValue(0x0, &zapcore.Field{Key:"_trace_id", Type:0xf, Integer:0, String:"8-U9SQ3ZSDicGNWWEk7mrg", Interface:interface {}(nil)}).WithCancel {a954d48e-079b-447e-bb8e-843f9f6965d1 c5041311-7656-49d3-a594-57df8fde4552 53efb07a-2edf-11e9-8e57-c85b76f42222} []]) at /home/michal/work/scylla/mermaid/src/github.com/scylladb/mermaid/sched/mock_runner_test.go:40 because: there are no expected calls of the method "Run" for that receiver
```

Signed-off-by: Michał Matczuk <michal@scylladb.com>